[lecture-7-hw]: Выполнено домашнее задание 6.
MrSmile4/ReactCourse pull request #6
Opened 2024-07-22 10:46 UTC by MrSmile4

2024-07-22 13:17 UTC, MrSmile4 commented
В ДЗ сказано "создать слайсы данных юзеров", у меня это "ReviewAuthor".

2024-07-23 10:35 UTC, zubkov7 requested changes

2024-07-23 10:35 UTC, zubkov7 commented on src/components/Restaurant/menu/menu-container.jsx
> +  const dish = useSelector((state) => selectDishById(state, menuId));
по неймингу есть смешение: селектор называется selectDishById, а передаем menuId. Правильно придерживаться одного нейминга

2024-07-23 10:35 UTC, zubkov7 commented on src/components/Restaurant/review-author/review-author-container.jsx
> +  const user = useSelector((state) => selectReviewAuthorById(state, userId));
тут все же мы селектим просто пользователя из стора, поэтому лучше применить нейминг selectUserById

2024-07-23 10:35 UTC, zubkov7 commented on src/components/app/App.jsx
> +  const [currentRestId, setCurrentRestId] = useState(undefined);
в таком кейсе при изменении состояния будет ререндериться все приложение, лучше унести логику в отдельный компонент

2024-07-23 10:35 UTC, zubkov7 commented on src/redux/etities/review-author.js
> +export const ReviewAuthorSlice = createSlice({
по идее это просто UserSlice, так как они могут существовать вне зависимости от отзывов

2024-07-24 11:29 UTC, MrSmile4 commented on src/components/Restaurant/menu/menu-container.jsx
> +  const dish = useSelector((state) => selectDishById(state, menuId));
переименовал prop

2024-07-24 11:30 UTC, MrSmile4 commented on src/components/Restaurant/review-author/review-author-container.jsx
> +  const user = useSelector((state) => selectReviewAuthorById(state, userId));
Хорошо, переименовал всё в User.

2024-07-24 11:30 UTC, MrSmile4 commented on src/components/app/App.jsx
> +  const [currentRestId, setCurrentRestId] = useState(undefined);
перенес к табам и засунул туда рестораны, такой вариант подойдет?

2024-07-24 13:49 UTC, zubkov7 commented on src/components/app/App.jsx
> +  const [currentRestId, setCurrentRestId] = useState(undefined);
да

2024-07-24 13:50 UTC, zubkov7 approved these changes

2024-07-25 09:52 UTC, merged